### ISSUE TITLE
36-bit file stored as octets

### ISSUE THREAD

**Issue by larsbrinkhoff** [mikpe/pdp10-tools#1]
Hello,

I would like to suggest this format for 36-bit words stored in octets.

36-bit word: AAAAAAABBBBBBBCCCCCCCDDDDDDDEEEEEEEF  
Octets: 0AAAAAAA 0BBBBBBB 0CCCCCCC 0DDDDDDD FEEEEEEE

The advantage of this format is that PDP-10 ASCII text files are readable as is in the octet format.  Also all words are always coded as five octets, so it's easy to seek in a file.

**Comment by mikpe** [comment]
I can see the utility of the change, but it will complicate buffering and conversion logic in the I/O layer (pdp10_stdio).
I'll keep it in mind, but don't expect a quick resolution as I'm focusing on the assembler currently, and then the linker.

**Comment by larsbrinkhoff** [comment]
Thanks for entertaining the suggestion.
